title: Homelab Dashboard
mode: dark_mode # options: dark_mode, light_mode, trans_light, trans_dark, service_mode
show_details: true # or false
background_url: https://your-image-url.com/background.jpg
groups: # each group will be a separate vertical section in the dashboard
  - title: Home Automation
    services:
      - iconUrl: https://www.home-assistant.io/images/favicon.ico
        ip: 192.168.1.10
        name: Home Assistant
        port: 8123
        url: http://192.168.1.10:8123

      - iconUrl: https://pi-hole.net/wp-content/uploads/2016/12/cropped-Vortex-R-192x192.png
        ip: 192.168.1.11
        name: Pi-hole
        port: 80
        url: http://192.168.1.11

  - title: Management
    services:
      - iconUrl: https://www.portainer.io/hubfs/favicon-96x96.png
        ip: 192.168.1.12
        name: Portainer
        port: 9000
        url: http://192.168.1.12:9000

      - iconUrl: https://syncthing.net/images/logo-128.png
        ip: 192.168.1.13
        name: Syncthing
        port: 8384
        url: http://192.168.1.13:8384
