services:
  dashboard:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./config.yml:/usr/share/nginx/html/config.yml
      - ./background.png:/usr/share/nginx/html/background.png
    restart: always
